"""commit

Revision ID: 1465bf50cf18
Revises: 5a9db319f165
Create Date: 2023-11-18 16:36:44.242677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1465bf50cf18'
down_revision: Union[str, None] = '5a9db319f165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_details', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('car_details_company_id_fkey', 'car_details', type_='foreignkey')
    op.create_foreign_key(None, 'car_details', 'user_login', ['user_id'], ['id'])
    op.drop_column('car_details', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_details', sa.Column('company_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'car_details', type_='foreignkey')
    op.create_foreign_key('car_details_company_id_fkey', 'car_details', 'user_login', ['company_id'], ['id'])
    op.drop_column('car_details', 'user_id')
    # ### end Alembic commands ###
