"""first commit

Revision ID: 159cf0e0a27a
Revises: 62844e2d4a36
Create Date: 2023-11-18 12:28:40.685987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '159cf0e0a27a'
down_revision: Union[str, None] = '62844e2d4a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login', sa.Column('phoneNumber', sa.String(length=9), nullable=False))
    op.add_column('user_login', sa.Column('password', sa.String(length=20), nullable=True))
    op.alter_column('user_login', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('user_login', 'surname',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('user_login', 'fin',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=7),
               existing_nullable=False)
    op.drop_index('ix_user_login_serial', table_name='user_login')
    op.create_index(op.f('ix_user_login_phoneNumber'), 'user_login', ['phoneNumber'], unique=True)
    op.drop_column('user_login', 'serial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login', sa.Column('serial', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_login_phoneNumber'), table_name='user_login')
    op.create_index('ix_user_login_serial', 'user_login', ['serial'], unique=False)
    op.alter_column('user_login', 'fin',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('user_login', 'surname',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('user_login', 'name',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('user_login', 'password')
    op.drop_column('user_login', 'phoneNumber')
    # ### end Alembic commands ###
