"""commit

Revision ID: 5a9db319f165
Revises: 2f7d78aaf74b
Create Date: 2023-11-18 16:21:55.128360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9db319f165'
down_revision: Union[str, None] = '2f7d78aaf74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_details',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('plateNumber', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=30), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['user_login.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_details_id'), 'car_details', ['id'], unique=True)
    op.create_index(op.f('ix_car_details_model'), 'car_details', ['model'], unique=True)
    op.create_index(op.f('ix_car_details_plateNumber'), 'car_details', ['plateNumber'], unique=True)
    op.create_index(op.f('ix_car_details_year'), 'car_details', ['year'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_details_year'), table_name='car_details')
    op.drop_index(op.f('ix_car_details_plateNumber'), table_name='car_details')
    op.drop_index(op.f('ix_car_details_model'), table_name='car_details')
    op.drop_index(op.f('ix_car_details_id'), table_name='car_details')
    op.drop_table('car_details')
    # ### end Alembic commands ###
