"""first commit

Revision ID: 62844e2d4a36
Revises: e4e173fa5526
Create Date: 2023-11-18 12:04:27.251222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62844e2d4a36'
down_revision: Union[str, None] = 'e4e173fa5526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('user_login', sa.Column('surname', sa.String(length=255), nullable=False))
    op.add_column('user_login', sa.Column('fin', sa.String(length=255), nullable=False))
    op.add_column('user_login', sa.Column('serial', sa.String(length=255), nullable=False))
    op.drop_index('ix_user_login_email', table_name='user_login')
    op.create_index(op.f('ix_user_login_fin'), 'user_login', ['fin'], unique=True)
    op.create_index(op.f('ix_user_login_name'), 'user_login', ['name'], unique=True)
    op.create_index(op.f('ix_user_login_serial'), 'user_login', ['serial'], unique=True)
    op.create_index(op.f('ix_user_login_surname'), 'user_login', ['surname'], unique=True)
    op.drop_column('user_login', 'email')
    op.drop_column('user_login', 'verified')
    op.drop_column('user_login', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('user_login', sa.Column('verified', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_login', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_login_surname'), table_name='user_login')
    op.drop_index(op.f('ix_user_login_serial'), table_name='user_login')
    op.drop_index(op.f('ix_user_login_name'), table_name='user_login')
    op.drop_index(op.f('ix_user_login_fin'), table_name='user_login')
    op.create_index('ix_user_login_email', 'user_login', ['email'], unique=False)
    op.drop_column('user_login', 'serial')
    op.drop_column('user_login', 'fin')
    op.drop_column('user_login', 'surname')
    op.drop_column('user_login', 'name')
    # ### end Alembic commands ###
